# This is a basic workflow to help you get started with Actions

name: Upload devcontainer to GHCR

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        
      - name: Build docker images
        run: docker build . -t docker.pkg.github.com/dwarak91/simplecalc/devcontainer:latest -f .devcontainer/Dockerfile
        
      - name: Log into registry
        run: echo ${{ secrets.cr_pat }} | docker login docker.pkg.github.com -u ${{github.actor}} --password-stdin
        
      - name: Push to GHCR
        run: docker push docker.pkg.github.com/dwarak91/simplecalc/devcontainer:latest
